AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: "AuthQueue"

  MyQueuePolicy:
    Type: "AWS::SQS::QueuePolicy"
    Properties:
      Queues:
        - !Ref MyQueue
      PolicyDocument:
        Version: "2012-10-17"
        Id: "__allow_sns_to_sqs_policy"
        Statement:
          - Sid: "AllowSnsToSendMessage"
            Effect: "Allow"
            Principal:
              Service: "sns.amazonaws.com"
            Action: "sqs:SendMessage"
            Resource: !GetAtt MyQueue.Arn
            Condition:
              StringEquals:
                "aws:SourceArn": "arn:aws:sns:us-east-1:813697295019:AuthenticationTopic"

# aws cloudformation create-stack --stack-name MySQSStack --template-body file://NotificationsIaC.yml